name : Create a commot on new issues

on : 
   issues : 
      types  : [opened]
jobs : 
   comment-with-action : 
      runs-on : ubuntu-latest
      steps : 
         - name : "dump github context"
           run : echo '${{ toJSON(github.event) }}' | jq
           shell : bash
         - name : Create comment
           uses : peter-evans/create-or-update-comment@v1
           with : 
              issue-number : ${{ github.event.issue.num}}
              body : | 
                 This is a multiline test comment 
                 - With Github **Markdown :spakles:
                 - Created by [create-or-update-comment][1]

                 [1]: https://github.com/peter-evans/create-or-update-comment
              reactions : '+1'   
