name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create comment using Action
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multiline test comment  
            - With GitHub **Markdown** âœ¨  
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment using GitHub API
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='Comment from the API call (not action)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
